import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

import { getTLDs } from '../../lib/get-tlds'

const latestTLDs = await getTLDs()

// this gets compiled and executed from '~/tool'
const validTLDsPath = resolve('src', 'lib', 'valid-tlds.mjs')

await writeFile(
  validTLDsPath,
  '// This file is automatically generated\nconst validTLDs = ' + JSON.stringify(latestTLDs, null, '  ') + '\n\nexport { validTLDs }\n',
  { encoding : 'utf8' })

// self-test results
const { validTLDs } = await import(validTLDsPath)
if (!validTLDs || validTLDs.com !== true) {
  throw new Error('Something went wrong with the TLD import (failed self-check).')
}
