RE_TMPL_GENERATOR_SRC_DIR:=$(SRC)/re-tmpl-generator
RE_TMPL_GENERATOR_SRC:=$(shell find $(RE_TMPL_GENERATOR_SRC_DIR) -name '*.mjs')
RE_TMPL_GENERATOR_MJS:=tools/re-tmpl-generator.mjs
RE_TMPL_GENERATOR_ENTRY:=$(RE_TMPL_GENERATOR_SRC_DIR)/index.mjs
BUILD_TARGETS+=$(RE_TMPL_GENERATOR_MJS)

$(RE_TMPL_GENERATOR_MJS): $(RE_TMPL_GENERATOR_SRC_DIR)/package-lock.json $(RE_TMPL_GENERATOR_SRC)
	cd $(RE_TMPL_GENERATOR_SRC_DIR) && npm i
	JS_PACKAGE_PATH=$(RE_TMPL_GENERATOR_SRC_DIR) \
	JS_BUILD_TARGET=$(RE_TMPL_GENERATOR_ENTRY) \
		$(SDLC_ROLLUP) --config $(SDLC_ROLLUP_CONFIG)
